package models

import (
	"go.mongodb.org/mongo-driver/bson/primitive"
)

// To-do list database model
type ToDoList struct {
	ID     primitive.ObjectID `json:"_id,omitempty" bson:"_id,omitempty"` // Generated by MongoDB. The type of ID in MongoDB is Object(id)
	Task   string             `json:"task,omitempty"`
	Status bool               `json:"status,omitempty"`
}
